DROP TABLE IF EXISTS ToDo;

CREATE TABLE ToDo(
	itemId INTEGER PRIMARY KEY,
	isPrivate BOOLEAN NOT NULL,
	user INTEGER NOT NULL,
	channel INTEGER,
	content NVARCHAR(255) NOT NULL,
	done BOOLEAN NOT NULL,
	creationDate DATETIME NOT NULL
);
